apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8888"
    prometheus.io/scrape: "true"
  name: {{ .Values.service.name }}
  namespace: {{ .Values.service.namespace }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Values.deployment.name }}-{{ .Values.deployment.env.environment }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.deployment.namespace }}
  labels:
    app: {{ .Values.deployment.name }}-{{ .Values.deployment.env.environment }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}-{{ .Values.deployment.env.environment }}
  template:
    metadata:
      annotations:
        timestamp: {{ .Values.timestamp }}
      labels:
        app: {{ .Values.deployment.name }}-{{ .Values.deployment.env.environment }}
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: {{ .Values.deployment.name }}
        image: peersyst/portal-web:{{ .Values.tagWeb }}
        imagePullPolicy: Always
        args: {{ .Values.deployment.args }}
        resources:
          requests:
            memory: {{ .Values.deployment.memoryRequest }}
            cpu: {{ .Values.deployment.cpuRequest }}
          limits:
            memory: {{ .Values.deployment.memoryLimit }}
            cpu: {{ .Values.deployment.cpuLimit }}
        ports:
        - containerPort: {{ .Values.deployment.port }}
