apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certificate }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '443'
    alb.ingress.kubernetes.io/load-balancer-name: {{ .Values.ingress.name }}-{{ .Values.deployment.env.environment }}
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path.portal-web: /
    alb.ingress.kubernetes.io/actions.portal-web: >
      {"type":"forward","forwardConfig":{"targetGroups":[{"serviceName":"portal-web","servicePort":"http","weight":20}]}}
    alb.ingress.kubernetes.io/actions.redirect-to-https: >
      {"Type":"redirect","RedirectConfig":{"Host":"next.bridge.xrplevm.org","Path":"/#{path}","Port":"443","Protocol":"HTTPS","Query":"#{query}","StatusCode":"HTTP_301"}}
  name: {{ .Values.ingress.name }}-{{ .Values.deployment.env.environment }}
  namespace: portal
spec:
  ingressClassName: alb
  rules:
  - host: next.bridge.xrplevm.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: redirect-to-https
            port:
              name: use-annotation
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: portal-web
            port:
              name: use-annotation
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8888"
    prometheus.io/scrape: "true"
  name: {{ .Values.service.name }}
  namespace: portal
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Values.deployment.name }}-{{ .Values.deployment.env.environment }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: portal
  labels:
    app: {{ .Values.deployment.name }}-{{ .Values.deployment.env.environment }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}-{{ .Values.deployment.env.environment }}
  template:
    metadata:
      annotations:
        timestamp: {{ .Values.timestamp }}
      labels:
        app: {{ .Values.deployment.name }}-{{ .Values.deployment.env.environment }}
    spec:
      containers:
      - name: {{ .Values.deployment.name }}
        image: peersyst/portal-web:{{ .Values.tag }}
        imagePullPolicy: Always
        args: {{ .Values.deployment.args }}
        resources:
          requests:
            memory: {{ .Values.deployment.memoryRequest }}
            cpu: {{ .Values.deployment.cpuRequest }}
          limits:
            memory: {{ .Values.deployment.memoryLimit }}
            cpu: {{ .Values.deployment.cpuLimit }}
        ports:
        - containerPort: {{ .Values.deployment.port }}
