name: "Build and deploy"

on:
  push:
    branches:
      - main

  #workflow_dispatch:
  #  inputs:
  #    environment:
  #      type: choice
  #      description: Environment where to deploy
  #      options:
  #      - privatenet
  #      - devnet

concurrency:
  # Cancel old runs if there is a new commit in the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-web:
    uses: ./.github/workflows/build-web.yaml
    secrets: inherit
    with:
      push: true
      target: release

  deploy:
    needs: build-web
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit
    with:
      #environment: ${{ github.event.inputs.environment }}
      environment: privatenet
