name: deploy

# Only trigger, when the build workflow succeeded
on:
  workflow_call:

permissions:
  # Needed to configure aws credentials step
  id-token: write
  contents: read

jobs:
  initial:
    name: 🎬 Initial
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      NOW: ${{ steps.env-vars.outputs.NOW }}
      TAG: ${{ steps.env-vars.outputs.TAG }}
    steps:
      # Define global vars that will be used through the pipeline
      - name: Defining global vars
        shell: bash
        id: env-vars
        run: |
          echo "NOW=$(TZ=':Europe/Madrid' date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT
          echo "TAG=${GITHUB_SHA:0:8}" >> $GITHUB_OUTPUT

      # Checkout repository under $GITHUB_WORKSPACE path
      - name: Repository checkout
        uses: actions/checkout@v4

      # Send initial Slack deployment message
      - name: 📬 Initial Slack deployment message
        shell: bash
        env:
          NOW: ${{ steps.env-vars.outputs.NOW }}
          TAG: ${{ steps.env-vars.outputs.TAG }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          echo "Send initial Slack message"
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"🎬 Starting *GENESYS* deployment - Commit: <https://github.com/Peersyst/genesys/commit/${TAG}|${TAG}> by ${GITHUB_ACTOR}\"}" ${SLACK_WEBHOOK_URL}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
    strategy:
      matrix:
        environment: ['staging']
      fail-fast: false
    timeout-minutes: 10
    needs: [initial]
    steps:
      # Checkout repository under $GITHUB_WORKSPACE path
      - name: Repository checkout
        uses: actions/checkout@v4
      # Assume gitHubdeploymentsRole AWS role
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::291847425310:role/gitHubDeploymentsRole
          role-session-name: deploymentsRole
          role-duration-seconds: 900
          aws-region: us-east-1
      # Kubectl and Helm install
      - name: Kubectl and Helm install
        shell: bash
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
          KUBE_VERSION: v1.27.4
          HELM_VERSION: v3.12.2
        run: |
          curl -Ls https://storage.googleapis.com/kubernetes-release/release/${KUBE_VERSION}/bin/linux/amd64/kubectl -o kubectl && chmod +x kubectl && mv kubectl /usr/local/bin/kubectl
          curl -Ls https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz -o helm-linux-amd64.tar.gz && tar -xzf helm-linux-amd64.tar.gz && mv linux-amd64/helm /usr/local/bin/helm
          echo ${KUBECONFIG} | base64 --decode > kubeconfig.yaml
          chmod 600 kubeconfig.yaml
          echo ${GITHUB_WORKSPACE}
          echo "KUBECONFIG=${GITHUB_WORKSPACE}/kubeconfig.yaml" >> $GITHUB_ENV

      # Helm deployment
      - name: Helm deployment
        working-directory: ./infra/chart
        shell: bash
        env:
          NOW: ${{ needs.initial.outputs.NOW }}
          TAG: ${{ needs.initial.outputs.TAG }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          KUBECONFIG: ${{ env.KUBECONFIG }}
        run: |
          envsubst < Chart.yaml > Chart-0.yaml
          mv Chart-0.yaml Chart.yaml
          kubectl config use-context peersyst-privatenet
          helm -n genesys upgrade ${{ matrix.environment }} ./ --install --atomic --wait --timeout 301s --values values/${{ matrix.environment }}.yaml --set-string timestamp=${NOW} --set-string tagIndexer=${TAG} --set-string tagApi=${TAG} --set-string tagWeb=${{ matrix.environment }}-${TAG} --debug

      # Send Slack message if any previous step has failed in this job
      - name: 📬 Failure job notification
        if: ${{ failure() }}
        shell: sh
        env:
          NOW: ${{ needs.initial.outputs.NOW }}
          TAG: ${{ needs.initial.outputs.TAG }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          echo "Send error Slack message"
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"❌ *GENESYS* ${GITHUB_JOB} job *FAILED*. Check pipeline logs <https://github.com/Peersyst/genesys/actions/runs/${GITHUB_RUN_ID}|here> - Commit: <https://github.com/Peersyst/genesys/commit/${TAG}|${TAG}> by ${GITHUB_ACTOR}\"}" ${SLACK_WEBHOOK_URL}

  final:
    name: 🏁 Final
    runs-on: ubuntu-latest
    timeout-minutes: 1
    needs: [initial, deploy]
    if: |
      always() &&
      !contains(join(needs.*.result, ','), 'failure')

    steps:
      # Send final Slack deployment message
      - name: 📬 Final Slack deployment message
        shell: bash
        env:
          TAG: ${{ needs.initial.outputs.TAG }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          echo "Send final Slack message"
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"🏁 *GENESYS* deployment *SUCCESSFULLY* - Commit: <https://github.com/Peersyst/genesys/commit/${TAG}|${TAG}> by ${GITHUB_ACTOR}\"}" ${SLACK_WEBHOOK_URL}
